# Generated by Django 5.2.1 on 2025-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '受講者'), ('instructor', 'インストラクター')], max_length=10),
        ),
    ]
