# Generated by Django 5.2.1 on 2025-06-03 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.IntegerField(choices=[(1, 'スキー'), (2, 'スノーボード')])),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('level', models.CharField(choices=[('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], max_length=20)),
                ('lesson_type', models.CharField(choices=[('private_lesson', 'プライベートレッスン')], max_length=20)),
                ('max_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time_slot', models.CharField(choices=[('morning', '午前'), ('afternoon', '午後'), ('full_day', '1日')], max_length=20)),
                ('ski_morning_price', models.IntegerField(blank=True, null=True)),
                ('ski_afternoon_price', models.IntegerField(blank=True, null=True)),
                ('ski_full_day_price', models.IntegerField(blank=True, null=True)),
                ('snowboard_morning_price', models.IntegerField(blank=True, null=True)),
                ('snowboard_afternoon_price', models.IntegerField(blank=True, null=True)),
                ('snowboard_full_day_price', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.activitytype')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('activity_type', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('lesson_type', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_histories_as_instructor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_histories_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.lessondetail')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkiResort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=100)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='ski_resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.skiresort'),
        ),
    ]
